# These options tell you the depth of the TOC and sectioning
#+OPTIONS: h:3 toc:nil num:3
# 
# Input latex preambles.  article_setup.tex should be in ~/texmf
#+LATEX_HEADER: \input article_setup
#+LATEX_HEADER: \usepackage[nottoc,numbib]{tocbibind}
# 
# Image locations: for html out use hpub, for pdf out use lpub (see below)
# If you store your /asl/ftp/pub/username files in the 
#  aslhugo tree at /aslhugo/static/pub/username you can use 
#  the same markdown syntax for local previewing as for the live web
#  site.  But, you need to replace ~/Git/aslhugo with what is
#  appropriate for your machine. 
#+LINK: lpub ~/Git/aslhugo/static/pub/chepplew/asl_sno/figs/
#+LINK: hpub https://asl.umbc.edu/pub/chepplew/asl_sno/figs/
# 
# Title of PDF file
#+TITLE: SNOs at ASL, Production and Analysis.

#+BEGIN_EXPORT HTML
+++
title =  "Simultaneous Nadir Observations at ASL."
date  =  "2017-06-01"
author = "C. L. Hepplewhite"
comment = true
+++
#+END_EXPORT
# +TOC: headlines 2
 

* Production of the SNO (Simultaneous Nadir Observations)

SNO data either come from JPL or are created at ASL.

** From JPL

<TBD>

** At ASL

Various scripts to create SNO pairs for two sensors from L1b/L1c or RTP data files.
Designed to be run as stand-alone scripts for single day processing or batch jobs
using control scripts.


SNO data can be created for IASI & CrIS, AIRS & CrIS and AIRS & IASI.
 - IASI & CrIS can be created from IASI L1C and CrIS CCAST L1C or RTP subsets.
 - AIRS & CrIS currently created from AIRS L1b, L1c and CrIS CCAST L1b
 - AIRS & IASI currently created from AIRS L1b and IASI L1C

   For each CrIS data set the spectral resolution can be either high or low resolution.

   For each IASI set there can be IASI-1 (MetOpA) or IASI-2 (MetOpB).

Standard data fields in the SNO files:
  Geolocation, latitude, longitude, time, satellite zenith, solar zenith angle, FOV.
  Radiance spectral data of the Observations, and in the the case of the RTP data also
  the calculated spectral radiance.

Special sets of SNOs have been created with AIRS spectral having been deconvolved to the
  CrIS spectral grid. After the AIRS L1b data are converted to CrIS the spectral radiances
  are concatenated into the SNO files. So these will have extra fields.
  
Data files are located in:
  /asl/s1/chepplew/data/sno/
  
* Detailed procedures  
** 1.1 IASI and CrIS 
*** IASI:CrIS from clear subset RTP.
- main script: function [] = make_IASI_CRIS_SNO_frmRTP.m(par1, par2, par3) 
  par1: the required date string with format: 'YYYY/MM/DD'
  par2: the model used to drive SARTA string. ERA or ECMWF.
  par3: the CrIS Spectral resolution, string. Options 'high','low'

- batch control script: function batch_IASI_CRIS_SNO_frmRTP()
  generates a slurm file from the driver file: jobDates.drv

- Driver file: jobDates.drv is a simple list of dates in YYYY/MM/DD<CR> format.

- The shell script that invokes the matlab script: batch_IASI_CRIS_SNO_frmRTP.sh
  Ensure par2 and par3 are set correctly here. 

  The batch script should be run from the matlab CLI prompt in the batchJobs/ 
  sub-directory, and the jobDates.drv can be a symbolic link to another file - 
  which I prefer to have a calendar month of dates listed. 


*** IASI:CrIS from CCAST L1 data at ASL.

- main script: function [] = make_IASI_CRIS_sno(par1,par2)
  par1: the required date string with format: 'YYYY/MM/DD'.
  par2: the CrIS spectral resolution to use, either 'high' or 'low'.
  
- batch control script: run_makeSNO_batch.m
  Requires a driver file of dates (usually jobDates.drv for a month worth)
  Ensure you select the appropriate CrIS spectral resolution to use here.
  and a slurm batch file: run_makeSNO_batch.slurm
  Ensure the slurm file has the correct number of arrays set and
  the main script is called.
  
- To run: in ./batchJobs $sbatch run_makeSNO_batch.slurm
  Generates output and error files, if successful saves MAT files in the data directories.
  
- Output files are stored at: /asl/s1/chepplew/data/sno/iasi_cris/{HR,LR}/YYYY/ 
  with names such as sno_iasi_cris_asl_yyyymmdd.mat
    
** 2.1 AIRS and CrIS 
*** AIRS:CrIS from L1b and CCAST at ASL.
- Main script: function [] = make_AIRS_CRIS_sno(par1, par2);
  par1: the required date string with format 'YYYY/MM/DD'
  par2: the CrIS spectral resolution to use, either 'high' or 'low'.
  
- batch control script: run_makeSNO_batch.m
  Requires a driver file of dates (usually jobDates.drv for a month worth)
  Ensure you select the appropriate CrIS spectral resolution to use here.
  and a slurm batch file: run_makeSNO_batch.slurm
  Ensure the slurm file has the correct number of arrays set and
  the main script is called. 

- Input Data:

- Output Data:

- Plotting and Analysis scripts:
 
*** AIRS:CrIS from L1c and CCAST at ASL:
- Main script: make_AIRS_CRIS_SNO_frmL1c.m  \\
 function [] = make_AIRS_CRIS_sno_frmL1c(req_date, cris_res)

- Batch Control: batch_AIRS_CRIS_SNO_frmL1.m  \\
  calling shell script: batch_AIRS_CRIS_SNO_frmL1.sh  \\
  with driver file: jobDates.drv which is a symbolic link to a month list of dates, e.g.
  jobDates_201301.drv  \\
  At run time creates the slurm batch file which assigns resources.

- Input Data: 

- Output Data:

- Plotting and Analysis Scripts:
 
** IASI and AIRS SNOs at ASL
*** TBD


